parameters:
  appbundle.album.provider.images_per_page: 9
  appbundle.album.provider.service.class: 'AppBundle\Services\AlbumProviderService'

services:
  appbundle.album.provider.service:
    class: "%appbundle.album.provider.service.class%"
    arguments:
      - "%appbundle.album.provider.images_per_page%"
      - "@doctrine.orm.entity_manager"